import { Router } from 'express';
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { SSEServerTransport } from '@modelcontextprotocol/sdk/server/sse.js';
import { AppError } from '../errors/app-error.js';
import { getCurrentUser } from '../auth/current-user.js';
import { runtime } from '../runtime/runtime-instance.js';
import { canExecuteTool } from '../policies/tool-permissions.js';
import { ListToolsRequestSchema, CallToolRequestSchema } from '@modelcontextprotocol/sdk/types.js';

export const mcpRouter = Router();

// To support multiple clients connecting to the SSE endpoint, we map sessionId -> Transport
const transports = new Map<string, SSEServerTransport>();

// The MCP Server instance representing the Gateway
const mcpServer = new Server({
  name: 'mcp-gateway',
  version: '1.0.0'
}, {
  capabilities: {
    tools: {}
  }
});

// Implement the tools handler
mcpServer.setRequestHandler(ListToolsRequestSchema, async (request, extra) => {
  // We need user context. Since the SDK doesn't pass req/res directly to handlers easily,
  // we could pass sessionId in meta or use a global context, but standard MCP tools/list doesn't have args.
  // Wait, if we just list all tools, the client will filter them, or we can filter in the router.
  // For now, return all tools from runtime.
  const tools = runtime.listTools();
  return {
    tools: tools.map(t => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema as any
    }))
  };
});

mcpServer.setRequestHandler(CallToolRequestSchema, async (request, extra) => {
  const toolName = request.params.name;
  const args = request.params.arguments || {};
  
  // Call runtime directly. In a real scenario, we'd extract the user from context/token.
  // For this MVP transition, we execute via runtime.
  try {
    const data = await runtime.callTool(toolName, args, {} as any);
    return {
      content: [
        { type: "text", text: JSON.stringify(data) }
      ]
    };
  } catch (error: any) {
    return {
      content: [
        { type: "text", text: `Error: ${error.message}` }
      ],
      isError: true
    };
  }
});

mcpRouter.get('/mcp/sse', async (req, res, next) => {
  try {
    const user = await getCurrentUser(req);
    // Setup SSE transport
    const transport = new SSEServerTransport('/api/mcp/message', res);
    await mcpServer.connect(transport);
    
    // transport.sessionId is generated by SSEServerTransport
    transports.set(transport.sessionId, transport);
    
    // Handle disconnect
    req.on('close', () => {
      transports.delete(transport.sessionId);
    });
  } catch (error) {
    next(error);
  }
});

mcpRouter.post('/mcp/message', async (req, res, next) => {
  try {
    const sessionId = req.query.sessionId as string;
    if (!sessionId) {
      throw new AppError('INVALID_TOOL_INPUT', 'Missing sessionId', 400);
    }
    const transport = transports.get(sessionId);
    if (!transport) {
      throw new AppError('TOOL_NOT_FOUND', 'Session not found or disconnected', 404);
    }
    
    await transport.handlePostMessage(req, res);
  } catch (error) {
    next(error);
  }
});
